package com.self.wx.auto.model;

import com.tuan.core.common.lang.TuanBaseDO;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table books
 *
 * @mbg.generated do_not_delete_during_merge 2018-03-19 10:54:45
 */
public class BooksDO extends TuanBaseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   图书名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bookname
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private String bookname;

    /**
     * Database Column Remarks:
     *   图书简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.introduction
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private String introduction;

    /**
     * Database Column Remarks:
     *   作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.author
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private String author;

    /**
     * Database Column Remarks:
     *   图书类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.menuid
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private String menuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.createtime
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private Integer createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.updatetime
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private Integer updatetime;

    /**
     * Database Column Remarks:
     *   kindle网盘地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.pan
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private String pan;

    /**
     * Database Column Remarks:
     *   点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.chan
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private Integer chan;

    /**
     * Database Column Remarks:
     *   图书添加者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.owner
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.source
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bookname
     *
     * @return the value of books.bookname
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bookname
     *
     * @param bookname the value for books.bookname
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.introduction
     *
     * @return the value of books.introduction
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.introduction
     *
     * @param introduction the value for books.introduction
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.author
     *
     * @return the value of books.author
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.author
     *
     * @param author the value for books.author
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.menuid
     *
     * @return the value of books.menuid
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public String getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.menuid
     *
     * @param menuid the value for books.menuid
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setMenuid(String menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.createtime
     *
     * @return the value of books.createtime
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public Integer getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.createtime
     *
     * @param createtime the value for books.createtime
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setCreatetime(Integer createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.updatetime
     *
     * @return the value of books.updatetime
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.updatetime
     *
     * @param updatetime the value for books.updatetime
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.pan
     *
     * @return the value of books.pan
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public String getPan() {
        return pan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.pan
     *
     * @param pan the value for books.pan
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setPan(String pan) {
        this.pan = pan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.chan
     *
     * @return the value of books.chan
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public Integer getChan() {
        return chan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.chan
     *
     * @param chan the value for books.chan
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setChan(Integer chan) {
        this.chan = chan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.owner
     *
     * @return the value of books.owner
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.owner
     *
     * @param owner the value for books.owner
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.source
     *
     * @return the value of books.source
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.source
     *
     * @param source the value for books.source
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    public void setSource(String source) {
        this.source = source;
    }
}