package com.self.wx.auto.dao;

import com.self.wx.auto.model.BooksDO;

import java.util.List;

public interface BooksDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    int insert(BooksDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    int insertSelective(BooksDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    BooksDO selectByPrimaryKey(Integer id);
    List<BooksDO> selectByName(String name);
    List<BooksDO> selectByType(String type);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    int updateByPrimaryKeySelective(BooksDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated 2018-03-19 10:54:45
     */
    int updateByPrimaryKey(BooksDO record);
}